/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#ffacbe',
        'surface-tint': '#ffb874',
        'inverse-on-surface': '#313032',
        'tertiary-fixed': '#ffd9e0',
        'primary': '#ffb874',
        'primary-fixed': '#ffe2c2',
        'on-tertiary-fixed': '#3f0018',
        'on-primary': '#4a2800',
        'on-error': '#690005',
        'primary-container': '#f7931a',
        'on-tertiary': '#66002b',
        'error-container': '#93000a',
        'secondary-container': '#00b954',
        'on-surface': '#e5e2e1',
        'on-tertiary-container': '#a10048',
        'on-secondary-fixed': '#002c15',
        'surface-container-lowest': '#0e0e0e',
        'surface-container': '#201f1f',
        'error': '#ffb4ab',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#353534',
        'surface-container-low': '#1c1b1b',
        'tertiary-fixed-dim': '#ffb1c2',
        'secondary-fixed': '#c2ffda',
        'on-secondary': '#003d1f',
        'on-secondary-fixed-variant': '#005c2f',
        'on-background': '#e5e2e1',
        'outline-variant': '#4a4543',
        'outline': '#9e9693',
        'background': '#131313',
        'surface-dim': '#131313',
        'on-tertiary-fixed-variant': '#8f0040',
        'on-surface-variant': '#c4c7c0',
        'on-secondary-container': '#d1ffdf',
        'primary-fixed-dim': '#f7931a',
        'surface-container-high': '#2a2a2a',
        'surface-bright': '#393939',
        'surface-variant': '#353534',
        'surface': '#131313',
        'on-primary-fixed-variant': '#6b4300',
        'secondary-fixed-dim': '#00b954',
        'secondary': '#00b954',
        'on-primary-fixed': '#2a1a00',
        'tertiary': '#ff8982',
        'inverse-primary': '#f7931a',
        'inverse-surface': '#e5e2e1',
        'on-primary-container': '#4a2800',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
